/**
 * Goods Form Configurations - All Annexures A-L
 * Based on REFINED_FORM_FIELDS_MANDATORY_OPTIONAL.md
 */

import { FormConfiguration, FormField, FormSection, APPLIANCE_TYPES } from '../types/formTypes';
import { goodsCommonFields } from './commonFieldsConfig';

/**
 * ANNEXURE A: APPLIANCES & ELECTRONICS
 * 26+ Mandatory + 5 Optional = 31+ Total
 */
export const appliances_electronicsForm: FormConfiguration = {
  id: 'goods_a_appliances',
  title: 'Appliances & Electronics',
  description: 'Form for selling appliances and electronic devices',
  category: 'goods',
  annexure: 'A',
  commonFields: goodsCommonFields,
  totalMandatory: 26,
  totalOptional: 5,
  totalFields: 31,
  sections: [
    {
      id: 'basic_info',
      title: 'Basic Information',
      order: 1,
      fields: [
        {
          id: 'appliance_type',
          label: 'Appliance Type',
          type: 'select',
          mandatory: true,
          options: APPLIANCE_TYPES.map(type => ({
            label: type,
            value: type.toLowerCase().replace(' ', '_'),
          })),
          order: 1,
          section: 'Appliance Selection',
          description: 'Select the type of appliance',
        },
        {
          id: 'brand',
          label: 'Brand',
          type: 'text',
          mandatory: true,
          maxLength: 100,
          order: 2,
          section: 'Specifications',
          description: 'Brand name of the appliance',
        },
        {
          id: 'model_number',
          label: 'Model Number',
          type: 'text',
          mandatory: true,
          maxLength: 100,
          order: 3,
          section: 'Specifications',
          description: 'Model number or code',
        },
        {
          id: 'capacity',
          label: 'Capacity',
          type: 'text',
          mandatory: true,
          maxLength: 100,
          order: 4,
          section: 'Specifications',
          description: 'Capacity (e.g., 5kg, 32 inch, etc.)',
        },
        {
          id: 'energy_rating',
          label: 'Energy Rating',
          type: 'select',
          mandatory: true,
          options: [
            { label: '1 Star', value: '1' },
            { label: '2 Stars', value: '2' },
            { label: '3 Stars', value: '3' },
            { label: '4 Stars', value: '4' },
            { label: '5 Stars', value: '5' },
          ],
          order: 5,
          section: 'Specifications',
          description: 'Energy efficiency rating',
        },
        {
          id: 'manufactured_year',
          label: 'Manufactured Year',
          type: 'number',
          mandatory: true,
          min: 1990,
          max: new Date().getFullYear(),
          order: 6,
          section: 'Specifications',
          description: 'Year of manufacture',
        },
      ],
    },
    {
      id: 'condition_usage',
      title: 'Condition & Usage',
      order: 2,
      fields: [
        {
          id: 'condition',
          label: 'Condition',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'New', value: 'new' },
            { label: 'Used', value: 'used' },
          ],
          order: 1,
          section: 'Condition',
          description: 'Is the appliance new or used?',
        },
        {
          id: 'age_months_or_years',
          label: 'Age (Months/Years)',
          type: 'text',
          mandatory: true,
          maxLength: 50,
          order: 2,
          section: 'Condition',
          condition: {
            type: 'IF',
            fieldName: 'condition',
            triggerValue: 'used',
          },
          description: 'How old is the appliance',
        },
        {
          id: 'usage_frequency',
          label: 'Usage Frequency',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Daily', value: 'daily' },
            { label: 'Weekly', value: 'weekly' },
            { label: 'Occasional', value: 'occasional' },
          ],
          order: 3,
          section: 'Condition',
          condition: {
            type: 'IF',
            fieldName: 'condition',
            triggerValue: 'used',
          },
          description: 'How frequently was it used',
        },
        {
          id: 'previous_repairs',
          label: 'Previous Repairs?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 4,
          section: 'Condition',
          condition: {
            type: 'IF',
            fieldName: 'condition',
            triggerValue: 'used',
          },
          description: 'Has the appliance been repaired before',
        },
        {
          id: 'warranty_remaining',
          label: 'Warranty Remaining?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 5,
          section: 'Condition',
          condition: {
            type: 'IF',
            fieldName: 'condition',
            triggerValue: 'used',
          },
          description: 'Is warranty still valid',
        },
        {
          id: 'if_warranty_remaining_months',
          label: 'Warranty Remaining Months',
          type: 'number',
          mandatory: false,
          min: 0,
          max: 60,
          order: 6,
          section: 'Condition',
          condition: {
            type: 'IF',
            fieldName: 'warranty_remaining',
            triggerValue: 'yes',
          },
          description: 'How many months of warranty remain',
        },
        {
          id: 'original_bill_available',
          label: 'Original Bill Available?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 7,
          section: 'Condition',
          condition: {
            type: 'IF',
            fieldName: 'condition',
            triggerValue: 'used',
          },
          description: 'Is the original purchase bill available',
        },
      ],
    },
    {
      id: 'appliance_tests',
      title: 'Appliance-Specific Tests',
      order: 3,
      fields: [
        // TV Fields
        {
          id: 'display_condition',
          label: 'Display Condition',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Perfect', value: 'perfect' },
            { label: 'Minor scratches', value: 'minor_scratches' },
            { label: 'Significant damage', value: 'significant_damage' },
          ],
          order: 1,
          section: 'TV-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'tv',
          },
          description: 'Condition of the TV display',
        },
        {
          id: 'dead_pixels_present',
          label: 'Dead Pixels Present?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 2,
          section: 'TV-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'tv',
          },
          description: 'Are there dead pixels on the screen',
        },
        {
          id: 'lines_shadow_light_bleed',
          label: 'Lines, Shadows, or Light Bleed?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 3,
          section: 'TV-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'tv',
          },
          description: 'Any display artifacts present',
        },
        {
          id: 'remote_working',
          label: 'Remote Working?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 4,
          section: 'TV-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'tv',
          },
          description: 'Is the remote control functioning',
        },
        {
          id: 'hdmi_ports_working',
          label: 'HDMI Ports Working?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 5,
          section: 'TV-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'tv',
          },
          description: 'Are HDMI ports working properly',
        },
        {
          id: 'speaker_working',
          label: 'Speaker Working?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 6,
          section: 'TV-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'tv',
          },
          description: 'Is the TV speaker working',
        },
        // AC Fields
        {
          id: 'cooling_test_passed',
          label: 'Cooling Test Passed?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 1,
          section: 'AC-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'ac',
          },
          description: 'Did the AC cool the room properly',
        },
        {
          id: 'compressor_replaced',
          label: 'Compressor Replaced?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 2,
          section: 'AC-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'ac',
          },
          description: 'Has the compressor been replaced',
        },
        {
          id: 'gas_refill_required',
          label: 'Gas Refill Required?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 3,
          section: 'AC-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'ac',
          },
          description: 'Does the AC need gas refill',
        },
        {
          id: 'pcb_replaced_ac',
          label: 'PCB Replaced?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 4,
          section: 'AC-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'ac',
          },
          description: 'Has the PCB been replaced',
        },
        {
          id: 'noise_level',
          label: 'Noise Level',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Normal', value: 'normal' },
            { label: 'Unusual', value: 'unusual' },
          ],
          order: 5,
          section: 'AC-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'ac',
          },
          description: 'Is the noise level normal for this AC model',
        },
        // Fridge Fields
        {
          id: 'cooling_test_passed_fridge',
          label: 'Cooling Test Passed?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 1,
          section: 'Fridge-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'fridge',
          },
          description: 'Does the fridge cool properly',
        },
        {
          id: 'compressor_condition',
          label: 'Compressor Condition',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Good', value: 'good' },
            { label: 'Fair', value: 'fair' },
            { label: 'Poor', value: 'poor' },
          ],
          order: 2,
          section: 'Fridge-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'fridge',
          },
          description: 'Condition of the compressor',
        },
        {
          id: 'door_seal_condition',
          label: 'Door Seal Condition',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Good', value: 'good' },
            { label: 'Fair', value: 'fair' },
            { label: 'Poor', value: 'poor' },
          ],
          order: 3,
          section: 'Fridge-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'fridge',
          },
          description: 'Condition of the door sealing',
        },
        {
          id: 'freezer_working',
          label: 'Freezer Working?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 4,
          section: 'Fridge-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'fridge',
          },
          description: 'Is the freezer compartment working',
        },
        {
          id: 'ice_maker_working',
          label: 'Ice Maker Working?',
          type: 'select',
          mandatory: true,
          options: [
            { label: 'Yes', value: 'yes' },
            { label: 'No', value: 'no' },
          ],
          order: 5,
          section: 'Fridge-Specific Tests',
          condition: {
            type: 'IF',
            fieldName: 'appliance_type',
            triggerValue: 'fridge',
          },
          description: 'Is the ice maker working (if available)',
        },
      ],
    },
    {
      id: 'seller_evidence',
      title: 'Mandatory Seller Evidence',
      order: 4,
      fields: [
        {
          id: 'function_test_video',
          label: 'Function Test Video',
          type: 'url',
          mandatory: true,
          order: 1,
          section: 'Evidence',
          description: 'Power ON + Working display/functionality + Noise check + Remote working',
        },
        {
          id: 'physical_condition_photos',
          label: 'Physical Condition Photos',
          type: 'url',
          mandatory: true,
          allowMultiple: true,
          order: 2,
          section: 'Evidence',
          description: 'Front + Back/side + Serial sticker + Dents/scratches closeup + Remote/panel + Power cable',
        },
        {
          id: 'capacity_rating_label_photo',
          label: 'Capacity Rating Label Photo',
          type: 'url',
          mandatory: true,
          order: 3,
          section: 'Evidence',
          description: 'Star rating + Energy guide + Capacity',
        },
        {
          id: 'previous_repairs_evidence',
          label: 'Previous Repairs Evidence',
          type: 'url',
          mandatory: false,
          order: 4,
          section: 'Evidence',
          condition: {
            type: 'IF',
            fieldName: 'previous_repairs',
            triggerValue: 'yes',
          },
          description: 'Bill + Service report + Warranty card',
        },
      ],
    },
  ],
  rules: [
    {
      type: 'REQUIRE_ALL_MANDATORY',
      description: 'All mandatory fields must be filled',
      affectedFields: [],
      implementation: (formData) => Object.values(formData).every(v => v !== null && v !== undefined && v !== ''),
    },
    {
      type: 'AUTO_CALCULATE',
      description: 'Calculate platform fee and total amount',
      affectedFields: ['sale_price', 'platform_fee', 'total_amount'],
      implementation: (formData) => {
        if (formData.sale_price) {
          formData.platform_fee = formData.sale_price * 0.01;
          formData.total_amount = formData.sale_price + formData.platform_fee;
          return true;
        }
        return false;
      },
    },
  ],
};

export default appliances_electronicsForm;
