export interface ContractGenerationParams {
  transactionType: 'goods' | 'services';
  amount: number;
  sellerName: string;
  buyerName: string;
  sellerPhone: string;
  buyerPhone: string;
  productName?: string;
  serviceDescription?: string;
  deliveryDate?: string;
  completionDate?: string;
  quantity?: string;
  location?: string;
  customLocation?: string;
  warranty?: string;
  returnPolicy?: string;
  specialTerms?: string;
}

export interface GeneratedContract {
  content: string;
  clauses: string[];
  riskAssessment: string;
  suggestions: string[];
}

export class AIContractService {
  private static readonly OPENAI_API_URL = 'https://api.openai.ai/v1/chat/completions';
  private static readonly ANTHROPIC_API_URL = 'https://api.anthropic.com/v1/messages';
  
  // For demo purposes, we'll use a sophisticated template system
  // In production, you'd integrate with actual AI services
  static async generateContract(params: ContractGenerationParams): Promise<GeneratedContract> {
    // Simulate AI processing time
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const contract = this.generateAdvancedContract(params);
    const clauses = this.generateSmartClauses(params);
    const riskAssessment = this.assessContractRisk(params);
    const suggestions = this.generateSuggestions(params);
    
    return {
      content: contract,
      clauses,
      riskAssessment,
      suggestions
    };
  }

  private static generateAdvancedContract(params: ContractGenerationParams): string {
    const isGoods = params.transactionType === 'goods';
    const currentDate = new Date().toLocaleDateString('en-IN');
    const agreementId = `AGR-${Date.now()}`;
    
    const escrowClause = this.generateEscrowClause(params.amount);
    const specificTerms = isGoods ? 
      this.generateGoodsSpecificTerms(params) : 
      this.generateServicesSpecificTerms(params);
    const paymentTerms = this.generatePaymentTerms(params);
    const disputeClause = this.generateDisputeClause(params);
    
    return `
# BHAROSE PE DIGITAL ESCROW AGREEMENT

**Agreement ID**: ${agreementId}  
**Date of Creation**: ${currentDate}  
**Generated by**: Bharose Pe AI Legal Assistant  

---

## PARTIES TO THE AGREEMENT

**SELLER (First Party)**  
Name: ${params.sellerName}  
Contact: ${params.sellerPhone}  
Role: Provider of ${isGoods ? 'goods' : 'services'}  

**BUYER (Second Party)**  
Name: ${params.buyerName}  
Contact: ${params.buyerPhone}  
Role: Recipient of ${isGoods ? 'goods' : 'services'}  

---

## TRANSACTION OVERVIEW

**Transaction Type**: ${isGoods ? 'Sale of Goods' : 'Service Agreement'}  
**Total Amount**: ₹${params.amount.toLocaleString('en-IN')}  
${isGoods ? `**Product**: ${params.productName || 'As specified'}  
**Quantity**: ${params.quantity || '1 unit'}  
**Expected Delivery**: ${params.deliveryDate ? new Date(params.deliveryDate).toLocaleDateString('en-IN') : 'As agreed'}` :
`**Service**: ${params.serviceDescription || 'As detailed'}  
**Completion Date**: ${params.completionDate ? new Date(params.completionDate).toLocaleDateString('en-IN') : 'As agreed'}  
**Service Location**: ${params.location === 'custom' ? params.customLocation : params.location || 'As specified'}`}

---

## ESCROW TERMS & CONDITIONS

${escrowClause}

---

## SPECIFIC TERMS

${specificTerms}

---

## PAYMENT TERMS

${paymentTerms}

---

## DISPUTE RESOLUTION

${disputeClause}

---

## CANCELLATION & REFUND POLICY

### Pre-Commencement Cancellation
- Either party may cancel this agreement with 24 hours written notice before ${isGoods ? 'shipping/dispatch' : 'service commencement'}
- Full refund will be processed within 3-5 business days
- No cancellation charges applicable

### Post-Commencement Cancellation
${isGoods ? 
`- Cancellation after dispatch subject to return shipping costs
- Goods must be returned in original condition
- Refund processed after quality inspection` :
`- Cancellation after service commencement based on work completed
- Payment released proportional to verified completion percentage
- Minimum 25% payment retained for initiated services`}

---

## LEGAL FRAMEWORK & GOVERNING LAW

This Agreement is constituted under and governed by:

### Primary Indian Legislation
1. **Indian Contract Act, 1872** - Sections 1, 2, 10-40 (Contract Formation & Performance)
2. **Sale of Goods Act, 1930** (for goods transactions) - Sections 1-66 (Sale of Goods, Warranties, Transfer of Ownership)
3. **Consumer Protection Act, 2019** - Sections 1-100 (Consumer Rights, Unfair Trade Practices)
4. **Information Technology Act, 2000** - Sections 1, 10A, 43, 72 (Digital Contracts, Data Protection)
5. **Bharatiya Nyaya Sanhita, 2023** - Criminal provisions

### Applicable Secondary Legislation
- Goods & Services Tax Act, 2017 (if GST applicable)
- Prevention of Money Laundering Rules, 2020 (for high-value transactions >₹5,00,000)
- Foreign Exchange Management Act (FEMA), 1999 (if applicable)
- Copyright Act, 1957 (for service IP transfers)
- Consumer Protection (E-Commerce) Rules, 2020 (for online transactions)
- Digital Personal Data Protection Act, 2023 (for personal data)

### Jurisdiction & Venue
- **Governing Law**: Laws of the Republic of India
- **Dispute Resolution**: District Consumer Redressal Commission OR Arbitration & Conciliation Act, 1996
- **Exclusive Venue**: Courts in **Mumbai, Maharashtra** (or as mutually agreed)
- **Choice of Law**: Indian law prevails. No waiver of statutory rights permitted.

---

## ESCROW TERMS & CONDITIONS

${escrowClause}

---

## SPECIFIC TERMS

${specificTerms}

---

## PAYMENT TERMS

${paymentTerms}

---

## DISPUTE RESOLUTION MECHANISM

${disputeClause}

---

## CANCELLATION & REFUND POLICY (Per Consumer Protection Act, 2019)

### Pre-Commencement Cancellation (Section 20, CPA 2019)
- Either party may cancel this agreement with 24 hours written notice before ${isGoods ? 'shipping/dispatch' : 'service commencement'}
- Full refund will be processed within 3-5 business days
- No cancellation charges applicable
- Refund per Consumer Protection Act, 2019 provisions

### Post-Commencement Cancellation
${isGoods ? 
`- Cancellation after dispatch subject to return shipping costs (Consumer Protection Act Rule 4)
- Goods must be returned in original condition within return period
- Refund processed after quality inspection (within 30 days maximum)
- Return shipping paid by Seller if goods non-conforming` :
`- Cancellation after service commencement based on verified work completion
- Payment released proportional to documented completion percentage per Section 40, Indian Contract Act
- Minimum 25% payment retained for initiated services as compensation
- Balance refund within 7 business days`}

---

## CONSUMER RIGHTS & PROTECTIONS

Per **Consumer Protection Act, 2019**:

1. **Right to Safety** - Goods/services shall be safe for use and free from defects
2. **Right to Information** - Full disclosure of product/service details, price, warranty
3. **Right to Choose** - Freedom to select goods/services and mode of payment
4. **Right to be Heard** - Right to file complaint with Consumer Redressal Commission
5. **Right to Redressal** - Entitled to compensation for losses due to defects/negligence
6. **Right to Consumer Education** - Access to information on consumer rights

**No Waiver Clause**: No clause herein shall exclude, restrict, or limit consumer rights under Consumer Protection Act, 2019. Void if in conflict with CPA statutory provisions.

---

## FORCE MAJEURE (Section 56, Indian Contract Act)

Per Section 56 (Impossibility of Performance) of Indian Contract Act, 1872:

Neither party shall be liable for delays or non-performance due to circumstances beyond reasonable control ("Act of God"), including but not limited to:
- Natural disasters, earthquakes, floods, pandemics, epidemics
- Government actions, wars, acts of terrorism, strikes
- Technical failures, internet outages, cyber attacks
- Transportation disruptions, lockdowns, quarantine mandates

**Notice Requirement**: Affected party must notify other party within 24 hours. Performance obligation resumes upon cessation of force majeure event.

---

## STATUTORY COMPLIANCE CERTIFICATIONS

### Anti-Corruption & Legal Compliance
- This transaction complies with Prevention of Corruption Act, 1988
- No unlawful consideration or illegal purposes involved
- Both parties confirm no conflict with existing laws

### Tax & Financial Compliance (if applicable)
- **GST**: If seller GST registered, GST @applicable rate per GST Act, 2017
- **TDS**: 30% TDS may apply per Income Tax Act, 1961 Section 194LA (if applicable)
- **PAN/Aadhaar**: High-value transactions require verification per FEMA Act, 1999

### Data Protection (DPDP Act, 2023)
- Personal data collected shall be processed per Digital Personal Data Protection Act, 2023
- Data used only for transaction purposes, not shared with third parties
- Right to data deletion upon request within 30 days of transaction completion

---

## ADDITIONAL TERMS & CONDITIONS

${params.specialTerms ? `**Special Terms & Conditions**: ${params.specialTerms}` : ''}
${params.warranty ? `**Warranty (Sections 14-15, SGA)**: ${params.warranty}` : ''}
${params.returnPolicy ? `**Return Policy (CPA Rules, 2020)**: ${params.returnPolicy}` : ''}

---

## SIGNATURES & ACCEPTANCE

### Digital Acceptance (IT Act 2000, Section 10A)
By digitally accepting via OTP/email/authorized digital means, both parties:
- Confirm they have read and understood ALL terms and conditions
- Confirm they have legal authority to enter into this agreement  
- Confirm all information provided is accurate, complete, and truthful
- Confirm they agree to be legally bound by these terms
- Confirm they consent to digital signature per IT Act, 2000

### Legal Effect
This digital acceptance constitutes valid contract formation per:
- Section 2(e) of Indian Contract Act (Consideration)
- Section 10 of Indian Contract Act (Offer & Acceptance)
- Section 10A of Information Technology Act, 2000 (Digital Contracts)

**Digital Signature Authentication**: Bharose Pe OTP Verification  
**Contract Execution Timestamp**: ${new Date().toISOString()}  
**Contract ID**: ${`AGR-${Date.now()}`}  

---

## LEGAL DISCLAIMER & RECOMMENDATIONS

🔍 **Important Notice**: 
This AI-generated agreement incorporates standard legal provisions and references to applicable Indian law. Both parties are **STRONGLY ADVISED** to:
- Review ALL clauses carefully before acceptance
- Consult with a qualified lawyer for transactions >₹10,00,000
- Verify counterparty identity and credentials
- Keep a copy of this agreement and all communications

**For Complex Transactions**: Transactions exceeding ₹50,00,000 or involving intellectual property, partnerships, or real estate MUST be reviewed by qualified legal counsel.

**Dispute Resolution Timeline**: Most disputes resolved within 45 days through Bharose Pe mediation. Consumer Commission disputes may take 90-180 days.

---

**Bharose Pe Digital Contracts | Secure, Legally Compliant Transactions**
*Powered by AI Legal Framework | Compliant with Indian Laws & International Best Practices*

**Bharose Pe Escrow Services Pvt. Ltd.**  
*Secure Digital Transactions Made Simple*
    `.trim();
  }

  private static generateEscrowClause(amount: number): string {
    const riskLevel = amount > 100000 ? 'high' : amount > 25000 ? 'medium' : 'low';
    
    return `
### Escrow Protection Mechanism
1. **Fund Security**: Total amount of ₹${amount.toLocaleString('en-IN')} will be held in Bharose Pe's secure escrow account
2. **Release Trigger**: Funds released only upon successful completion and buyer confirmation
3. **Inspection Period**: ${riskLevel === 'high' ? '7 business days' : riskLevel === 'medium' ? '5 business days' : '3 business days'} for review
4. **Multi-level Verification**: ${riskLevel === 'high' ? 'Enhanced KYC and transaction monitoring' : 'Standard verification process'}
5. **Insurance Coverage**: Transactions above ₹50,000 covered under Bharose Pe protection policy
    `.trim();
  }

  private static generateGoodsSpecificTerms(params: ContractGenerationParams): string {
    return `
### GOODS DELIVERY & QUALITY TERMS

#### Delivery Obligations
- Seller must ship/deliver goods within 24-48 hours of payment confirmation
- Proper packaging required to prevent damage during transit
- Tracking details to be shared with buyer immediately upon dispatch
- Delivery must be completed by ${params.deliveryDate ? new Date(params.deliveryDate).toLocaleDateString('en-IN') : 'agreed date'}

#### Quality Assurance
- Goods must exactly match description, images, and specifications provided
- All accessories, documentation, and original packaging must be included
- For electronics: IMEI/Serial numbers must match pre-purchase verification
- Authenticity guarantee with return option if goods prove counterfeit

#### Inspection Rights
- Buyer has right to inspect goods upon delivery
- Any defects or discrepancies must be reported within inspection period
- Seller responsible for replacement/refund if goods don't meet specifications
- Return shipping costs borne by seller for non-conforming goods
    `.trim();
  }

  private static generateServicesSpecificTerms(params: ContractGenerationParams): string {
    return `
### SERVICE DELIVERY & QUALITY TERMS

#### Service Obligations  
- Service provider must commence work within 24 hours of payment confirmation
- Regular progress updates to be provided to client
- Service must be completed by ${params.completionDate ? new Date(params.completionDate).toLocaleDateString('en-IN') : 'agreed date'}
- All work must meet professional industry standards

#### Scope & Deliverables
- Service includes: ${params.serviceDescription || 'As detailed in communications'}
- Deliverables to be provided in agreed format and quality
- Up to 2 rounds of reasonable revisions included
- Additional work outside scope requires separate agreement and payment

#### Quality Standards
- Work must meet specifications agreed upon before commencement  
- Professional standards and best practices must be followed
- Client has right to request corrections for work not meeting specifications
- Intellectual property rights transferred upon final payment release
    `.trim();
  }

  private static generatePaymentTerms(params: ContractGenerationParams): string {
    const milestones = params.amount > 50000 ? 
      'Payment may be released in milestones for high-value transactions' :
      'Single payment release upon completion';
      
    return `
### Payment Schedule & Terms
1. **Escrow Deposit**: Full payment deposited in escrow before service/delivery commencement
2. **Release Mechanism**: ${milestones}
3. **Processing Time**: 2-3 business days for fund release after confirmation
4. **Transaction Fees**: As per Bharose Pe fee structure (disclosed upfront)
5. **Refund Processing**: 3-5 business days for approved refunds
6. **Currency**: All amounts in Indian Rupees (INR)
    `.trim();
  }

  private static generateDisputeClause(params: ContractGenerationParams): string {
    return `
### Dispute Resolution Mechanism
1. **Primary Resolution**: Good faith negotiation between parties (7 days)
2. **Bharose Pe Mediation**: Platform-assisted mediation with dedicated resolution team
3. **Evidence Submission**: Both parties may submit supporting documents/communications
4. **Expert Opinion**: Technical experts may be consulted for complex disputes
5. **Final Decision**: Bharose Pe reserves right to make binding decisions in unresolved disputes
6. **Fund Protection**: Disputed amounts remain in escrow until resolution
7. **Appeal Process**: 48-hour window for appealing resolution decisions
    `.trim();
  }

  private static generateSmartClauses(params: ContractGenerationParams): string[] {
    const clauses = [
      "Bharose Pe Escrow Protection",
      "Digital Signature Authentication",
      "Quality Assurance Guarantee",
      "Dispute Resolution Mechanism"
    ];

    if (params.amount > 50000) {
      clauses.push("Enhanced KYC Verification", "Insurance Coverage");
    }

    if (params.transactionType === 'goods') {
      clauses.push("Delivery Tracking", "Return & Refund Rights");
    } else {
      clauses.push("Service Milestone Tracking", "Revision Rights");
    }

    return clauses;
  }

  private static assessContractRisk(params: ContractGenerationParams): string {
    const riskFactors = [];
    
    if (params.amount > 100000) {
      riskFactors.push("High-value transaction requires enhanced verification");
    }
    
    if (!params.deliveryDate && !params.completionDate) {
      riskFactors.push("Consider setting specific completion timeline");
    }
    
    if (params.transactionType === 'services' && !params.serviceDescription) {
      riskFactors.push("Detailed service description recommended");
    }

    return riskFactors.length > 0 ? 
      `Medium Risk: ${riskFactors.join(', ')}` : 
      "Low Risk: Well-structured transaction with standard terms";
  }

  private static generateSuggestions(params: ContractGenerationParams): string[] {
    const suggestions = [];
    
    if (params.amount > 25000) {
      suggestions.push("Consider insurance coverage for high-value transactions");
    }
    
    if (params.transactionType === 'goods' && !params.warranty) {
      suggestions.push("Add warranty terms for better buyer protection");
    }
    
    if (!params.specialTerms) {
      suggestions.push("Add any specific terms or conditions unique to this transaction");
    }
    
    suggestions.push("Review all terms carefully before final acceptance");
    suggestions.push("Save a copy of this agreement for your records");
    
    return suggestions;
  }

  // Future: Real AI integration methods
  static async generateWithOpenAI(params: ContractGenerationParams, apiKey: string): Promise<string> {
    // Implementation for OpenAI integration
    throw new Error("OpenAI integration not yet implemented");
  }

  static async generateWithClaude(params: ContractGenerationParams, apiKey: string): Promise<string> {
    // Implementation for Anthropic Claude integration  
    throw new Error("Claude integration not yet implemented");
  }
}