/**
 * Common Fields Configurations - Inherited by all Goods Categories
 * Based on REFINED_FORM_FIELDS_MANDATORY_OPTIONAL.md
 */

import { FormField, FieldOption, DELIVERY_METHODS, RETURN_OPTIONS, INSPECTION_WINDOW_OPTIONS } from '../types/formTypes';

/**
 * GOODS COMMON FIELDS - 15 Mandatory
 */
export const goodsCommonFields: FormField[] = [
  {
    id: 'product_name',
    label: 'Product Name/Title',
    type: 'text',
    placeholder: 'Enter product name',
    mandatory: true,
    maxLength: 200,
    order: 1,
    section: 'Basic Information',
    description: 'Item name/title for the product',
  },
  {
    id: 'brand',
    label: 'Brand Name',
    type: 'text',
    placeholder: 'Enter brand name',
    mandatory: true,
    maxLength: 100,
    order: 2,
    section: 'Basic Information',
    description: 'Brand name of the product',
  },
  {
    id: 'description',
    label: 'Detailed Description',
    type: 'textarea',
    placeholder: 'Enter detailed description of the product',
    mandatory: true,
    maxLength: 1000,
    order: 3,
    section: 'Basic Information',
    description: 'Comprehensive description of the product condition and features',
  },
  {
    id: 'condition_category',
    label: 'Overall Condition',
    type: 'select',
    mandatory: true,
    options: [
      { label: 'New', value: 'new' },
      { label: 'Like New', value: 'like_new' },
      { label: 'Excellent', value: 'excellent' },
      { label: 'Good', value: 'good' },
      { label: 'Fair', value: 'fair' },
      { label: 'Poor', value: 'poor' },
    ],
    order: 4,
    section: 'Basic Information',
    description: 'Overall condition category of the product',
  },
  {
    id: 'color',
    label: 'Color/Finish',
    type: 'text',
    placeholder: 'Enter color or finish type',
    mandatory: true,
    maxLength: 100,
    order: 5,
    section: 'Basic Information',
    description: 'Color or finish of the product',
  },
  {
    id: 'sale_price',
    label: 'Sale Price (₹)',
    type: 'number',
    placeholder: '0.00',
    mandatory: true,
    min: 0,
    order: 6,
    section: 'Pricing & Delivery',
    description: 'Sale price in Indian Rupees',
  },
  {
    id: 'delivery_method',
    label: 'Delivery Method',
    type: 'select',
    mandatory: true,
    options: DELIVERY_METHODS.map(method => ({
      label: method.charAt(0).toUpperCase() + method.slice(1),
      value: method.toLowerCase(),
    })),
    order: 7,
    section: 'Pricing & Delivery',
    description: 'How will the product be delivered',
  },
  {
    id: 'delivery_address',
    label: 'Delivery Address',
    type: 'textarea',
    placeholder: 'Enter complete delivery address',
    mandatory: true,
    maxLength: 500,
    order: 8,
    section: 'Pricing & Delivery',
    description: 'Full address where the product will be delivered',
  },
  {
    id: 'delivery_date',
    label: 'Delivery Date',
    type: 'date',
    mandatory: true,
    order: 9,
    section: 'Pricing & Delivery',
    description: 'When will the product be delivered',
  },
  {
    id: 'warranty_status',
    label: 'Warranty Status',
    type: 'select',
    mandatory: true,
    options: [
      { label: 'Warranty Present', value: 'present' },
      { label: 'Warranty Expired', value: 'expired' },
      { label: 'No Warranty', value: 'none' },
    ],
    order: 10,
    section: 'Warranty & Evidence',
    description: 'Current warranty status of the product',
  },
  {
    id: 'warranty_valid_till',
    label: 'Warranty Valid Till',
    type: 'date',
    mandatory: true,
    order: 11,
    section: 'Warranty & Evidence',
    description: 'Warranty expiry date',
  },
  {
    id: 'buyer_evidence_recording',
    label: 'Buyer Evidence Recording Required?',
    type: 'select',
    mandatory: true,
    options: [
      { label: 'Yes', value: 'yes' },
      { label: 'No', value: 'no' },
    ],
    order: 12,
    section: 'Warranty & Evidence',
    description: 'Will buyer record evidence videos/photos?',
    disclaimer: 'Recording buyer evidence (unboxing, functionality tests, condition verification) is always preferable for strong evidence points.',
  },
  {
    id: 'what_to_record',
    label: 'What to Record',
    type: 'multi-select',
    mandatory: true,
    options: [
      { label: 'Unboxing video', value: 'unboxing_video' },
      { label: 'Power ON test', value: 'power_on_test' },
      { label: 'Functionality test', value: 'functionality_test' },
      { label: 'Physical condition inspection', value: 'physical_condition' },
      { label: 'Serial/model number verification', value: 'serial_verification' },
      { label: 'Sound/display test', value: 'sound_display_test' },
      { label: 'All accessories check', value: 'accessories_check' },
      { label: 'Other (specify)', value: 'other' },
    ],
    order: 13,
    section: 'Warranty & Evidence',
    condition: {
      type: 'IF',
      fieldName: 'buyer_evidence_recording',
      triggerValue: 'yes',
    },
    description: 'Select items buyer should record as evidence',
  },
  {
    id: 'seller_predispatch_recording',
    label: 'Seller Pre-Dispatch Recording Required?',
    type: 'select',
    mandatory: true,
    options: [
      { label: 'Yes', value: 'yes' },
      { label: 'No', value: 'no' },
    ],
    order: 14,
    section: 'Warranty & Evidence',
    description: 'Will seller record pre-dispatch videos?',
    disclaimer: 'Pre-dispatch recording videos showing packaging, condition verification, and handling are always preferable for strong evidence points.',
  },
  {
    id: 'predispatch_recording_items',
    label: 'Pre-Dispatch Recording Items',
    type: 'multi-select',
    mandatory: true,
    options: [
      { label: 'Full product packaging video', value: 'packaging_video' },
      { label: 'Product condition walkthrough', value: 'condition_walkthrough' },
      { label: 'Serial number/label verification', value: 'serial_verification' },
      { label: 'Accessories verification (all items included)', value: 'accessories_verification' },
      { label: 'Box sealing/security verification', value: 'box_sealing' },
      { label: 'Final weight/dimension check', value: 'weight_dimension' },
      { label: 'Handling instructions demonstration', value: 'handling_demo' },
      { label: 'Other (specify)', value: 'other' },
    ],
    order: 15,
    section: 'Warranty & Evidence',
    condition: {
      type: 'IF',
      fieldName: 'seller_predispatch_recording',
      triggerValue: 'yes',
    },
    description: 'Select items seller should record',
  },
  {
    id: 'return_accepted',
    label: 'Return Policy',
    type: 'select',
    mandatory: true,
    options: [
      { label: 'Yes - Full returns accepted', value: 'yes' },
      { label: 'No - No returns accepted', value: 'no' },
      { label: 'Partial - Returns accepted only if damaged/defective', value: 'partial' },
    ],
    order: 16,
    section: 'Return Policy',
    description: 'Return acceptance policy',
  },
  {
    id: 'return_condition_description',
    label: 'Return Conditions',
    type: 'textarea',
    mandatory: true,
    maxLength: 500,
    order: 17,
    section: 'Return Policy',
    condition: {
      type: 'IF',
      fieldName: 'return_accepted',
      triggerValue: ['yes', 'partial'],
    },
    description: 'Specify exact conditions under which returns are accepted',
  },
  {
    id: 'return_shipping_paid_by',
    label: 'Return Shipping Paid By',
    type: 'select',
    mandatory: true,
    options: [
      { label: 'Buyer', value: 'buyer' },
      { label: 'Seller', value: 'seller' },
      { label: 'Mutual agreement based on case', value: 'mutual' },
    ],
    order: 18,
    section: 'Return Policy',
    condition: {
      type: 'IF',
      fieldName: 'return_accepted',
      triggerValue: ['yes', 'partial'],
    },
    description: 'Who pays for return shipping',
  },
  {
    id: 'return_refund_timeline_days',
    label: 'Refund Timeline (Days)',
    type: 'number',
    mandatory: true,
    min: 1,
    max: 365,
    order: 19,
    section: 'Return Policy',
    condition: {
      type: 'IF',
      fieldName: 'return_accepted',
      triggerValue: ['yes', 'partial'],
    },
    description: 'Days to process refund after return received',
  },
  {
    id: 'inspection_window_hours',
    label: 'Inspection Window',
    type: 'select',
    mandatory: true,
    options: INSPECTION_WINDOW_OPTIONS.map(option => ({
      label: option,
      value: option.toLowerCase().replace(' ', '_'),
    })),
    order: 20,
    section: 'Delivery Inspection',
    description: 'Hours buyer has to inspect item after receipt',
  },
];

/**
 * SERVICE COMMON FIELDS - 4 Mandatory
 */
export const serviceCommonFields: FormField[] = [
  {
    id: 'service_price',
    label: 'Service Price (₹)',
    type: 'number',
    placeholder: '0.00',
    mandatory: true,
    min: 0,
    order: 1,
    section: 'Service Details',
    description: 'Total service cost in Indian Rupees',
  },
  {
    id: 'payment_schedule',
    label: 'Payment Schedule',
    type: 'select',
    mandatory: true,
    options: [
      { label: 'Full upfront', value: 'full_upfront' },
      { label: 'Partial upfront', value: 'partial_upfront' },
      { label: 'On delivery', value: 'on_delivery' },
      { label: 'Milestone-based', value: 'milestone_based' },
    ],
    order: 2,
    section: 'Service Details',
    description: 'When will payment be made',
  },
  {
    id: 'delivery_date',
    label: 'Agreed Completion Date',
    type: 'date',
    mandatory: true,
    order: 3,
    section: 'Service Details',
    description: 'Agreed date for service completion',
  },
  {
    id: 'dispute_resolution_days',
    label: 'Dispute Resolution Days',
    type: 'number',
    mandatory: true,
    min: 1,
    max: 365,
    defaultValue: 30,
    order: 4,
    section: 'Service Details',
    description: 'Days allowed for resolution (default: 30)',
  },
];

export default {
  goodsCommonFields,
  serviceCommonFields,
};
