// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izyhokrfpnyynohmrtvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eWhva3JmcG55eW5vaG1ydHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzExNDgsImV4cCI6MjA3MjkwNzE0OH0.i9VDuui-PQ82leMcZPcMtCRNTwU6x4f-_bGCWbibOjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});