// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thscwfnlxiwdzubgrqgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoc2N3Zm5seGl3ZHp1YmdycWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTkzNTAsImV4cCI6MjA3NDQ3NTM1MH0.dW8TAEoTXq1hekB3C1ESDmlz5ss7xqXpLPjEtEb51DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});